[workspace]
members = [
    "src/pool_canister",
    "src/claim_canister",
]
exclude = [
    "src/commons"
]
resolver = "2"

[workspace.dependencies]
getrandom = { version = "0.2", features = ["js"] }

